name: Deploy React App Windows

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code (opcional)
        uses: actions/checkout@v4  

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull React image from GHCR
        shell: powershell
        run: |
          $repo = "${{ github.repository }}".ToLower()
          $imageName = "ghcr.io/$repo/ui:latest"
          Write-Host "Pulling image: $imageName"
          docker pull $imageName

      - name: Create .env file from ENV_FILE variable
        shell: powershell
        run: |
          $envContent = @"
          ${{ vars.ENV_FILE }}
          "@
          Set-Content -Path .env -Value $envContent
          Write-Host "Contenido del .env creado:"
          Get-Content .env

      - name: Stop and remove existing container
        shell: powershell
        run: |
          docker ps -a -q -f name=react_app | ForEach-Object { docker rm -f $_ }
          Write-Host "Old container removed (if any)."

      - name: Run React container with .env
        shell: powershell
        run: |
          $imageName = "ghcr.io/$(${{ github.repository }}.ToLower())/ui:latest"
          docker ps -a -q -f name=react_app | ForEach-Object { docker rm -f $_ }
          Write-Host "Iniciando contenedor React con variables de entorno"
          docker run -d `
            -p 3000:80 `
            --env-file .env `
            --name react_app `
            --restart unless-stopped `
            $imageName
