name: Build image

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          echo "REACT_APP_API_ENV value: ${{ vars.REACT_APP_API_ENV }}"
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/${REPO_LOWER}/ui
          docker build --no-cache --build-arg REACT_APP_API_ENV="${{ vars.REACT_APP_API_ENV }}" -t $IMAGE_NAME -f Dockerfile .

      - name: Push Docker image to GitHub Container Registry
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/${REPO_LOWER}/ui
          docker push $IMAGE_NAME